accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_pk>/', views.user, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    
]

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns =[
    path('', views.index, name="index"),
    path('<int:movie_pk>/', views.detail, name="detail"),
    path('<int:movie_pk>/reviews/new/', views.new, name='new'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/like/', views.like, name='like')
]

pjt10/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls'))
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    followings = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='followers',
        blank=True
    )

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)

class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)  

movies/forms.py
from django import forms
from . models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'score',)

accounts/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
# Create your views here.
def index(request):
    User = get_user_model()
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request,'accounts/index.html', context)

def log_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def log_out(request):
    auth_logout(request)
    return redirect('accounts:index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')
    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()
    context= {
        'form' : form
    }
    return render(request, 'accounts/form.html', context)

def user(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    context=  {
        'user' : user
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, user_pk):
    User = get_user_model()
    follower = get_object_or_404(User, pk=user_pk)
    if request.user in follower.followers.all():
        follower.followers.remove(request.user)
    else:
        follower.followers.add(request.user)
    return redirect('accounts:profile', user_pk)

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . models import Genre, Movie, Review
from django.contrib.auth.decorators import login_required
from . forms import ReviewForm
from IPython import embed

# Create your views here.

def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'movies/index.html', context)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    reviews = Review.objects.filter(movie_id=movie_pk)
    form = ReviewForm()
    context = {
        'movie': movie,
        'reviews': reviews,
        'form': form
    }
    return render(request, 'movies/detail.html', context)

@login_required
def new(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    form = ReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.user = request.user
        review.movie = movie
        review.save()
    return redirect('movies:detail', movie.pk)
        
@login_required
def delete(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    review.delete()
    return redirect('movies:detail', movie_pk)

@login_required
def like(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.user in movie.like_users.all():
        movie.like_users.remove(request.user)
    else:
        movie.like_users.add(request.user)
    return redirect('movies:detail', movie_pk)

accounts/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="">게시판</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <!-- 로그인이 되어 있다면, -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout'%}">로그아웃</a>
        </li>
        {% else %}
        <!-- 로그인이 되어 있지 않다면, -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login'%}">로그인</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup'%}">회원가입</a>
          </li>
      {% endif %}
    </ul>
  </div>
</nav>

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<form action = "" method = "post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type='submit' class='btn btn-primary'>Submit</button>  
  {% endbuttons %}
</form> 
{% endblock %} 

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block body %}
  {% for user in users %}
  <a href="{% url 'accounts:profile' user.pk %}"><h3>{{user}}</h3></a>
  {% endfor %}
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <h2>ID : {{user.username}}</h2> 
  <hr>
  <h3>평점 정보</h3><br>
  <table style='width:50%'>
    <tr>
      <th><h3>내용</h3></th>
      <th ><h3>평점</h3></th>
      <th><h3>영화 제목</h3></th>
    </tr>
    <tr>
      {% for review in user.review_set.all %}
      <td>{{ review.content }}</td> 
      <td >{{ review.score}}</td> 
      <td>{{review.movie.title}}</td>
  {% endfor %}
  </tr>
  </table>
  <hr>
  <h3>좋아하는 영화 정보</h3><br>
  {% for movie in user.like_movies.all %}
    <p>{{movie.title}}</p>
  {% endfor %}
  <hr>
  <h3>팔로우 수 / 팔로잉 한 사람의 수</h3> 
  <br>
  {% with user.followers.all as followers %}
  <h3>{{user.followings.all.count}} / {{followers|length}}</h3>
  {% if request.user != user %}
    {% if user in follwers %}
    <a href="{% url 'accounts:follow' user.id %}"><h3>팔로잉취소</h3></a>
    {% else %}
    <a href="{% url 'accounts:follow' user.id %}"><h3>팔로잉</h3></a>
    {% endif %}
  {% endif %}
  {% endwith %}
  <hr>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  {% include '_navbar.html' %}
  <div class="container">
    {% block body %}
    {% endblock%}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <title>Movie</title>
  {% block css %}
  {% endblock%}
</head>
<body>
  {% include '_navbar.html' %}
  {% block body %}
  {% endblock %}
  <script src="https://kit.fontawesome.com/f7a84a7607.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block body %}

  <div class="container">
    <div class="row">
      <div class="col-8">
          <h2>
            {{movie.title}}
            {% if user in movie.like_users.all %}
              <a href="{% url 'movies:like' movie.pk %}"><i class="fas fa-star" style=" color: yellow;"></i></a>
            {% else %}
              <a href="{% url 'movies:like' movie.pk %}"><i class="far fa-star" style=" color: yellow;"></i></a>
            {% endif %}
          </h2> 
          <p>{{movie.audience}}</p>
          <p>{{movie.genre.name}}</p>
      </div>
      <div class="col-4">
          <img width="100%" src="{{movie.poster_url}}" alt="{{movie.title}}">
      </div>
    </div><hr>
    <div>
      <p>{{movie.description}}</p>
    </div><hr>
    <div>
      <h2> 평점 </h2>
      {% for review in reviews %}
        작성자 : {{ review.user }} |
        평점 : {{ review.score }} |
        {{ review.content }}
      {% if user == review.user %}
      <form action="{% url 'movies:delete' movie.pk review.pk%}" method="POST" style="display:inline">
        {% csrf_token %}
          <button>댓글삭제</button>
      </form> <br>
      {% endif %}

      {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <form action="{% url 'movies:new' movie.pk%}" method="POST">
      {% csrf_token %}
      {{form}}
      <input type="submit" value="댓글 등록">
    </form>
    {% endif %}
    
  </div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block body %}
<div class="container">
  <div class="row">
    {% for movie in movies %}
    <div class="col-3 mt-4">
      <a href="{% url 'movies:detail' movie.pk%}">
        <img width="100%" src="{{movie.poster_url}}" alt="{{movie.title}}">
      </a>
    </div>
    {% endfor %}
  </div>
</div>  

{% endblock %}